# Generated by Django 3.1.2 on 2021-03-14 21:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('waste_type', models.CharField(max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=4)),
                ('transacted_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('stars', models.IntegerField(default=0)),
                ('transaction_state', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=None, max_length=50)),
                ('area', models.CharField(default=None, max_length=50)),
                ('road', models.CharField(default=None, max_length=50)),
                ('contact', models.CharField(default=None, max_length=50)),
                ('location_coords', models.CharField(default=None, max_length=50)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
